### ISSUE TITLE
Geobytes geocoding: ArgumentError (invalid byte sequence in UTF-8)

### ISSUE THREAD

**Issue by jmmontero1** [geokit/geokit#212]
Hi,

I just had a strange behavior using geobytes to geocode an IP address. I got an invalid byte sequence in UTF-8 in my rails application. As far as I have seen, there is a method to ensure that what is returned to rails is UTF-8 but only in the ip geocoder. Would it be possible to apply it as well to geobytes?

For more info I am sending the stack trace of the error (changing the ip address to 123.123.123.123):

2018-02-16T21:01:44.883156+00:00 app[web.1]: D, [2018-02-16T21:01:44.883053 #6] DEBUG -- : [679e410e-6ead-4172-a3f7-42dfb4cbb387] Geobytes geocoding. address: 123.123.123.123, args []
2018-02-16T21:01:45.095027+00:00 app[web.1]: D, [2018-02-16T21:01:45.094912 #6] DEBUG -- : [679e410e-6ead-4172-a3f7-42dfb4cbb387] Geobytes geocoding. Result: %7B%22geobytesforwarderfor%22%3A%22%22%2C%22geobytesremoteip%22%3A%2254.78.99.165%22%2C%22geobytesipaddress%22%3A%22123.123.123.123%22%2C%22geobytescertainty%22%3A%22100%22%2C%22geobytesinternet%22%3A%22ES%22%2C%22geobytescountry%22%3A%22Spain%22%2C%22geobytesregionlocationcode%22%3A%22ESCT%22%2C%22geobytesregion%22%3A%22Catalu%F1a%22%2C%22geobytescode%22%3A%22CT%22%2C%22geobyteslocationcode%22%3A%22ESCTBARC%22%2C%22geobytesdma%22%3A%220%22%2C%22geobytescity%22%3A%22Barcelona%22%2C%22geobytescityid%22%3A%223807%22%2C%22geobytesfqcn%22%3A%22Barcelona%2C+CT%2C+Spain%22%2C%22geobyteslatitude%22%3A%2241.382999%22%2C%22geobyteslongitude%22%3A%222.183000%22%2C%22geobytescapital%22%3A%22Madrid%22%2C%22geobytestimezone%22%3A%22%2B01%3A00%22%2C%22geobytesnationalitysingular%22%3A%22Spanish%22%2C%22geobytespopulation%22%3A%2240037995%22%2C%22geobytesnationalityplural%22%3A%22Spaniards%22%2C%22geobytesmapreference%22%3A%22Europe+%22%2C%22geobytescurrency%22%3A%22Euro%22%2C%22geobytescurrencycode%22%3A%22EUR%22%2C%22geobytestitle%22%3A%22Spain%22%7D
2018-02-16T21:01:45.099339+00:00 app[web.1]: I, [2018-02-16T21:01:45.099267 #6]  INFO -- : [679e410e-6ead-4172-a3f7-42dfb4cbb387] Completed 500 Internal Server Error in 218ms
2018-02-16T21:01:45.101451+00:00 app[web.1]: F, [2018-02-16T21:01:45.101384 #6] FATAL -- : [679e410e-6ead-4172-a3f7-42dfb4cbb387]   
2018-02-16T21:01:45.101571+00:00 app[web.1]: F, [2018-02-16T21:01:45.101504 #6] FATAL -- : [679e410e-6ead-4172-a3f7-42dfb4cbb387] ArgumentError (invalid byte sequence in UTF-8):
2018-02-16T21:01:45.101649+00:00 app[web.1]: F, [2018-02-16T21:01:45.101595 #6] FATAL -- : [679e410e-6ead-4172-a3f7-42dfb4cbb387]   
2018-02-16T21:01:45.101829+00:00 app[web.1]: F, [2018-02-16T21:01:45.101742 #6] FATAL -- : [679e410e-6ead-4172-a3f7-42dfb4cbb387] vendor/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:447:in `count'
2018-02-16T21:01:45.101832+00:00 app[web.1]: [679e410e-6ead-4172-a3f7-42dfb4cbb387] vendor/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:447:in `binary?'
2018-02-16T21:01:45.101834+00:00 app[web.1]: [679e410e-6ead-4172-a3f7-42dfb4cbb387] vendor/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:316:in `visit_String'
2018-02-16T21:01:45.101835+00:00 app[web.1]: [679e410e-6ead-4172-a3f7-42dfb4cbb387] vendor/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:163:in `accept'
2018-02-16T21:01:45.101837+00:00 app[web.1]: [679e410e-6ead-4172-a3f7-42dfb4cbb387] vendor/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:580:in `block in emit_coder'
2018-02-16T21:01:45.101839+00:00 app[web.1]: [679e410e-6ead-4172-a3f7-42dfb4cbb387] vendor/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:578:in `each'
2018-02-16T21:01:45.101840+00:00 app[web.1]: [679e410e-6ead-4172-a3f7-42dfb4cbb387] vendor/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:578:in `emit_coder'
2018-02-16T21:01:45.101842+00:00 app[web.1]: [679e410e-6ead-4172-a3f7-42dfb4cbb387] vendor/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:563:in `dump_coder'
2018-02-16T21:01:45.101845+00:00 app[web.1]: [679e410e-6ead-4172-a3f7-42dfb4cbb387] vendor/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:127:in `push'
2018-02-16T21:01:45.101843+00:00 app[web.1]: [679e410e-6ead-4172-a3f7-42dfb4cbb387] vendor/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:161:in `accept'
2018-02-16T21:01:45.101846+00:00 app[web.1]: [679e410e-6ead-4172-a3f7-42dfb4cbb387] vendor/ruby-2.3.1/lib/ruby/2.3.0/psych.rb:416:in `dump'
2018-02-16T21:01:45.101848+00:00 app[web.1]: [679e410e-6ead-4172-a3f7-42dfb4cbb387] vendor/ruby-2.3.1/lib/ruby/2.3.0/psych/core_ext.rb:15:in `psych_to_yaml'
2018-02-16T21:01:45.101850+00:00 app[web.1]: [679e410e-6ead-4172-a3f7-42dfb4cbb387] vendor/bundle/ruby/2.3.0/gems/geokit-rails-2.3.0/lib/geokit-rails/ip_geocode_lookup.rb:31:in `store_ip_location'

For more info, the line where it fails is:
Geocoders::MultiGeocoder.geocode(ip_address).success.to_yaml

Best regards,
Jaime

**Comment by aaronpark** [comment]
I got the sale for the following command Geocoder.search("20.779549,-156.323508")

This is a place in Hawaii
